Data Structures and Algorithms/Data Structures/Queue.py
=> Queue Program

Contributors.md, Data Structures and Algorithms/Algorithms/InsertionSort.py
Added Insertion sort in Python
=> Added Insertion sort in Python

Data Structures and Algorithms/Algorithms/RatInAMaze.cpp
Added a code that solves the 'rat in a maze' algorithm by backtracking.
=> Added 'Rat in a Maze' algorithm in cpp

App Development/android-hello-world/app/src/main/java/com/sqisland/android/hello/MainActivity.java, Competitive Programming/CF-1408-D-Searchlights.cpp
Contest Name: Grakn Forces 2020
Link to the problem : https://codeforces.com/contest/1408/problem/D
=> Added Solution to CF-1408-D-Searchlights problem

Hello World Programs/hello world.py
added python program for printing hello world
=> Create hello world.py

Competitive Programming/atCoderDpSolution
=> AtCoderDpSolution

Web Development/index.html
A new folder for web developers and a landing page of hacktoberfest 2020
=> Added webd folder and landingpage

Hello World Programs/helloworld.java
=> added helloworld.java

Hello World Programs/Hello.java
=> Add Java file

Hello World Programs/hello_world.hs
Added hello world program in Haskell to Hello World Programs folder
=> Added hello world program in Haskell to Hello World Programs folder

Competitive Programming/Practice(Div.2 A)/TreeAndQueries_CF_375D.cpp
Solution for Tree and Queries (375-D) from codeforces 
https://codeforces.com/contest/375/problem/D
=> Cp Problems

Competitive Programming/AtCoder_DP_Sushi.py
Python3 solution to atcoder dp contest problem - Sushi
=> Solution to atcoder dp contest problem added

IoT & Robotics/Arduino Music/Raw Structure, IoT & Robotics/Section added by prashantkatiyar9777.txt
Folder will include the codes of Arduino, R-pi and Python and ROS related stuff. 
Added Arduino Music Code Project. Song Name : Coffin Dance
=> IoT and Robotics Division

Hello World Programs/helloWorld.c
Added hello world program in C.
=> hello world

Competitive Programming/(A) Captain Flint and Crew Recruitment.h
This file contains the code in c++ language for the problem (A) Captain Flint and Crew Recruitment.h of Codeforces Round #660 (Div. 2).
=>  Codeforces Round #660 (Div. 2)

Competitive Programming/brute_Force_Pattern_Match.cpp
Added Brute Force Algorithm to Competitive Programming folder.
=> Brute Force Algo

Python/selection sort.py
=> Adding new branch

Competitive Programming/CodeChef DSA Learning Series/Basic WarmUp/Carvans.cpp, Competitive Programming/CodeChef DSA Learning Series/Basic WarmUp/Lapindromes.cpp, Competitive Programming/CodeChef DSA Learning Series/Basic WarmUp/LifeTheUniverseAndEverything.cpp, Competitive Programming/CodeChef DSA Learning Series/Basic WarmUp/ReverseTheNumber.cpp, Competitive Programming/CodeChef DSA Learning Series/Basic WarmUp/SmartPhone.cpp
Added some solutions to the DSA Learning Series on CodeChef.
=> WarmUp challenge of DSA Learning Series

Student_admission.py
ML program to decide whether the student gets admission or not based on marks of 2 subjects.
=> Create student admission.py

Projects/Miltary Scanning Radar System/index.html, Projects/Miltary Scanning Radar System/style.css, Web Development/Animation Login Screen/index.html, Web Development/Animation Login Screen/script.js, Web Development/Animation Login Screen/style.css
**@bajajvinamr please merge this to your repo**
=> Create Animated Login Page in Web Development Folder

Python/Palindrome.py, Python/check_palindrome.py
added program to check if string is palindrome or not, python language
=> Check palindrome Python

Data Structures and Algorithms/Algorithms/fibonacci_recursive.py
=> recursive fibonacci

Projects/chatbot/README.md, Projects/chatbot/moodchatbot.py, Python/hangman/README.md, Python/hangman/hangman1.py
here i added a chatbot which is easy to impliment
=> chatbot added

Hello World Programs/hello_world.rs
#1 I added a hello world program in rust.
=> Added Hello world in rust file

Contributors.md, IoT & Robotics/OkGoogleArduino/OkGoogleArduino.ino, IoT & Robotics/OkGoogleArduino/README.md
Control your electronics with an Google Assistant + Arduino UNO + ESP8266
=> Google Assistant with Arduino UNO and ESP8266 

Data Structures and Algorithms/Algorithms/binarySearch.java, Data Structures and Algorithms/Algorithms/linearSearch.java
Added Algo with recursion method in java
=> Added Binary and Linear Search Algo

Contributors.md
Hello,
I have added my name in the Contributers list.
=> Added name to Contibuters.md

IoT & Robotics/door-opener/README.md, IoT & Robotics/door-opener/dors.ino
simple door opener with arduino, ultrasonic sensor and servo
=> add robotic project

Competitive Programming/CF_1370.cpp
Solution for Binary Subsequence Rotation
https://codeforces.com/contest/1370/problem/E
=> CF_1370.cpp

Competitive Programming/CF_1373.cpp
Solution for D. Maximum Sum on Even Positions
https://codeforces.com/contest/1373/problem/D
=> CF_1373.cpp

Competitive Programming/CF_1374.cpp
Solution for E1. Reading Books (easy version)
https://codeforces.com/contest/1374/problem/E1
=> CF_1374.cpp

Data Structures and Algorithms/Algorithms/String_to_Number.cpp
Program to convert a string to a number
=> String_to_Number.cpp

Data Structures and Algorithms/Data Structures/CircularLinkedList.c, Data Structures and Algorithms/Data Structures/DoublyLinkedLists.c
**I** have implemented All the basic operations which are used in DLL(Doubly Linked Lists ) for e.g  Insert Begin , Insert End  , Insert After Specific  , Insert Before Specific  , Delete Begin , Delete End , Delete after Specific  .  And same as for  SCL(Singly Circular Linked List ) > All the programs are written by my own and i have tested them several times and there is no ambiguity . Hope you will merge them  after a wise look  : ) .  @hacktober - fest 2020
=> Added DoublyLInkedLists & Circular Linked Lists

Data Structures and Algorithms/Algorithms/Multisource bfs/Codechef  -  Snakes and transition from Capitalism to Socialism.cpp, Data Structures and Algorithms/Algorithms/Multisource bfs/Codeforces  - Christmas Trees.cpp, Data Structures and Algorithms/Algorithms/Multisource bfs/Spoj - BITMAP - Bitmap.cpp
I have added a very famous algorithm that is derived from BFS, which is Multisource BFS. It contains three problems and their solutions from Codechef, Codeforces, and Spoj.
=> Multisource-BFS Added

Data Structures and Algorithms/Algorithms/djikstra.c, Python/rulingpair.py
=> djikstra algorithm

Competitive Programming/CSES_Twosets
Hi there, I have added problems of two sets form CSES! Hope everyone enjoys the solution
=> Added problems of twoset form CSES

Competitive Programming/Code for Group Stage.java
https://www.codechef.com/problems/UCL
Link to the problem
=> Codechef Beginners Problem-UCL

Data Structures and Algorithms/Algorithms/bubble_sort.c
Added the code for bubble sort in C programming
=> Added bubble_sort.c

Python/mapit.py
Simple python3 program to ease the use of google maps
=> added mapit.py

Python/bubble_sort.py
=> Added bubble sort in python

Node.JS/sum of 100
The program shows the sum of the massive that consists of 1-99
=> Create sum of 100

Python/assistant.py
Hi, I am adding python based speech recognition project.
=> Adding python based assistant project

Web Development/Simple_Login_Register/index.html, Web Development/Simple_Login_Register_form/index.html
a simple login & register form html with bootstrap 4
=> added a simple login & register form html 

Python/fetch_github_info.py
Added Script will fetch Github Info using `GITHUB USER API`
=> Fetch Github Info Script (Python)

Data Structures and Algorithms/Algorithms/c/selection_sort.c
Added c programming code for selection sort
=> Added selection_sort.c

Hello World Programs/helloworld by choudhary.c
i followed your into and made this hello world thannks
=> Create helloworld by choudhary.c

Python/Json Data Read.py
read any json file having its own url link
=> Create Json Data Read.py

Python/torrent_downloader.py
=> added torrent downloader

goroutines_sorting.go, tatus
=> Go program for sorting

Python/armstrong.py, Python/fibonacci.py, Python/lcm.py, Python/power.py, Python/prime.py
I have made these python programs to find out or to calculate simple math problems like finding the Fibonacci series, prime numbers, LCM, etc.
=> Python programs to find solutions for some simple math problems.

Data Structures and Algorithms/Data Structures/c/simple-link-list
program has the following modules:
• Insert a record into the database.
• Delete a record from the database
• Find a Record into the database
• Update a Record 
• Display the records of all the Employee belong to particular city/State/Country/Pin
• Generate report
=> simple-link-list

Python/Jumbled Words/Jumbled_words.py
Python game
Fixed #488 
Fixed #1
=> Jumbled_words game

Data Structures and Algorithms/Data Structures/c/heap_sort.c
Added heap_sort.c into c directory
=> Added heap_sort.c

Perimeter and area of Triangle
Program to find area and perimeter of a triangle/java program.
=> Perimeter and area of Triangle

Competitive Programming/decimalToBinary.java
java code to convert the given decimal number to binary without using any inbuilt functions
=> decimalToBinary without using inbuilt functions

Data Structures and Algorithms/Data Structures/doublee_linkedlist.cpp
menu driven program of doublee linked list. please add my file
=> doublee_linkedlist.cpp

Data Structures and Algorithms/Algorithms/MinimumSpanningTree.cpp
Minimum Spanning Tree algorithm added in /data structures and algorithms/algorithms
=> MST algorithm added

Data Structures and Algorithms/Algorithms/linearSearch.java
A linear search or sequential search is a method for finding an element within a list. It sequentially checks each element of the list until a match is found or the whole list has been searched.
=> Linear Search in java.

Data Structures and Algorithms/Algorithms/linearSearch.java
A linear search or sequential search is a method for finding an element within a list. It sequentially checks each element of the list until a match is found or the whole list has been searched.
=> My Linear Search program.

Hello World Programs/Hello_World.dart
Added a dart file which displays Hello World.
=> Added Hello_World.dart file

Data Structures and Algorithms/Algorithms/bucker_Sort.cpp
=> bucker_Sort.cpp

max and second max of n numbers
=> Create max and second max of n numbers

Python/frequent_element.py
=> added frequent element in an array program

CONTRIBUTORS.md
Reverts bajajvinamr/HacktoberFest2020#241
=> Revert "Create CONTRIBUTORS.md"

Data Structures and Algorithms/Algorithms/C#/merge_sort.cs
Created Merge Sort Algorithm on C#
=> Created Merge Sort Algorithm

Python/flask-app-hello-world.py
=> Add flask app 'hello world'

Web Development/Color-guessing/bootstrap.css, Web Development/Color-guessing/cg.css, Web Development/Color-guessing/cg.js, Web Development/Color-guessing/index.html
What u need to do is to guess the color by its RGB value
=> color guessing game added
